stages:
  data_ingestion:
    cmd: python src/deepCNNClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/deepCNNClassifier/pipeline/stage_01_data_ingestion.py
      - configs/config.yaml
    outs:
      - artifacts/data_ingestion/PetImages

  prepare_base_model:
    cmd: python src/deepCNNClassifier/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/deepCNNClassifier/pipeline/stage_02_prepare_base_model.py
      - configs/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model


  training:
    cmd: python src/deepCNNClassifier/pipeline/stage_04_training.py
    deps:
      - src/deepCNNClassifier/pipeline/stage_04_training.py
      - src/deepCNNClassifier/components/prepare_callbacks.py
      - configs/config.yaml
      - artifacts/data_ingestion/PetImages
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5

  evaluation:
    cmd: python src/deepCNNClassifier/pipeline/stage_05_evaluation.py
    deps:
      - src/deepCNNClassifier/pipeline/stage_05_evaluation.py
      - configs/config.yaml
      - artifacts/data_ingestion/PetImages
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
      - scores.json:
          cache: false