from deepCNNClassifier.components.data_ingestion import DataIngestion 
from deepCNNClassifier.components.prepare_base_model import PrepareBaseModel
from deepCNNClassifier.components.prepare_callbacks import PrepareCallback
from deepCNNClassifier.components.training import Training
from deepCNNClassifier.components.evaluation import Evaluation